"""Core domain models for PCIP.

Everything the platform touches — Canva designs, licensed assets, AI
generations, campaign briefs, pipeline runs, publications — is represented
here and stored as nodes/edges in the knowledge graph (see pcip.graph.store).
"""

from __future__ import annotations

import json
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def new_id(prefix: str) -> str:
    return f"{prefix}_{uuid.uuid4().hex[:12]}"


# ─── Graph vocabulary ────────────────────────────────────────────────────────


class NodeKind(str, Enum):
    """Types of nodes in the knowledge graph."""

    DESIGN = "design"                # a Canva design
    ASSET = "asset"                  # an image/video/audio asset (Canva or generated)
    FOLDER = "folder"                # a Canva folder
    BRAND_KIT = "brand_kit"          # a Canva Brand Kit
    BRAND_TEMPLATE = "brand_template"
    BRIEF = "brief"                  # a creative brief
    CAMPAIGN = "campaign"            # a multi-deliverable campaign
    PIPELINE_RUN = "pipeline_run"    # one execution of a pipeline
    OUTPUT = "output"                # a finished deliverable (exported file)
    PUBLICATION = "publication"      # a published instance on a channel
    CHANNEL = "channel"              # a publishing destination
    TOPIC = "topic"                  # subject-matter tag (e.g. "diabetes")
    BRAND = "brand"                  # a Pascual enterprise brand/entity


class EdgeKind(str, Enum):
    """Typed relationships between nodes."""

    CONTAINS = "contains"            # folder → design/asset
    USES_ASSET = "uses_asset"        # design/output → asset
    DERIVED_FROM = "derived_from"    # output → design, resized → original
    ON_BRAND = "on_brand"            # design/output → brand
    ABOUT = "about"                  # anything → topic
    PART_OF = "part_of"              # deliverable → campaign
    PRODUCED = "produced"            # pipeline_run → output
    FROM_BRIEF = "from_brief"        # pipeline_run → brief
    PUBLISHED_TO = "published_to"    # output → publication
    ON_CHANNEL = "on_channel"        # publication → channel
    FROM_TEMPLATE = "from_template"  # design → brand_template


# ─── Licensing ───────────────────────────────────────────────────────────────


class LicenseType(str, Enum):
    """Provenance/terms classification for every asset PCIP touches.

    The licensing policy engine (pcip.licensing) keys all decisions off this.
    """

    OWNED = "owned"                    # created by the org; full rights
    CANVA_FREE = "canva_free"          # Canva free content, used within a design
    CANVA_PRO = "canva_pro"            # Canva Pro/premium content (stock, elements)
    AI_GENERATED = "ai_generated"      # generated by an AI provider for the org
    THIRD_PARTY = "third_party"        # externally licensed (stock site, contract)
    UNKNOWN = "unknown"                # provenance not yet established


@dataclass
class License:
    """A license record attached to an asset."""

    type: LicenseType = LicenseType.UNKNOWN
    source: str = ""                   # e.g. "canva", "vertex-imagen", "shutterstock"
    terms_url: str = ""
    licensee: str = "PassQual"
    acquired_at: str = field(default_factory=now_iso)
    notes: str = ""

    def to_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        d["type"] = self.type.value
        return d

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "License":
        d = dict(d)
        d["type"] = LicenseType(d.get("type", "unknown"))
        return cls(**d)


# ─── Assets & deliverables ───────────────────────────────────────────────────


@dataclass
class Asset:
    """A visual/audio asset known to the platform."""

    id: str = field(default_factory=lambda: new_id("asset"))
    name: str = ""
    kind: str = "image"                # image | video | audio | font | other
    canva_id: str = ""                 # Canva asset/design id when applicable
    url: str = ""                      # retrieval URL (may be time-limited)
    local_path: str = ""
    license: License = field(default_factory=License)
    tags: List[str] = field(default_factory=list)
    created_at: str = field(default_factory=now_iso)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        d["license"] = self.license.to_dict()
        return d

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "Asset":
        d = dict(d)
        d["license"] = License.from_dict(d.get("license", {}))
        return cls(**d)


class Channel(str, Enum):
    """Publishing destinations PCIP knows how to route to."""

    WORDPRESS = "wordpress"        # passqual.com
    INSTAGRAM = "instagram"
    FACEBOOK = "facebook"
    LINKEDIN = "linkedin"
    YOUTUBE = "youtube"
    TIKTOK = "tiktok"
    X = "x"
    THREADS = "threads"
    NEWSLETTER = "newsletter"
    PODCAST = "podcast"


@dataclass
class Publication:
    """A record of one output published to one channel."""

    id: str = field(default_factory=lambda: new_id("pub"))
    output_id: str = ""
    channel: Channel = Channel.WORDPRESS
    url: str = ""
    external_id: str = ""
    published_at: str = field(default_factory=now_iso)
    status: str = "published"          # published | scheduled | failed
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        d["channel"] = self.channel.value
        return d


# ─── Briefs ──────────────────────────────────────────────────────────────────


@dataclass
class Brief:
    """A creative brief — the single input every pipeline starts from."""

    id: str = field(default_factory=lambda: new_id("brief"))
    title: str = ""
    objective: str = ""                # what this deliverable must achieve
    audience: str = ""                 # e.g. "patients 55+, low health literacy"
    brand: str = "PassQual"            # which enterprise brand this is for
    key_messages: List[str] = field(default_factory=list)
    channels: List[str] = field(default_factory=list)   # Channel values
    topics: List[str] = field(default_factory=list)
    language: str = "en"               # en | es | bilingual
    tone: str = ""
    references: List[str] = field(default_factory=list)  # graph node ids / URLs
    constraints: List[str] = field(default_factory=list)
    created_at: str = field(default_factory=now_iso)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "Brief":
        known = {f for f in cls.__dataclass_fields__}  # type: ignore[attr-defined]
        return cls(**{k: v for k, v in d.items() if k in known})

    @classmethod
    def from_json_file(cls, path: str) -> "Brief":
        with open(path, "r", encoding="utf-8") as fh:
            return cls.from_dict(json.load(fh))


# ─── Pipeline execution records ──────────────────────────────────────────────


@dataclass
class StepResult:
    step: str
    status: str = "pending"            # pending | running | done | failed | awaiting_review | rejected
    detail: str = ""
    outputs: List[str] = field(default_factory=list)   # node ids produced
    started_at: str = ""
    finished_at: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class PipelineRun:
    id: str = field(default_factory=lambda: new_id("run"))
    pipeline: str = ""
    brief_id: str = ""
    status: str = "pending"            # pending | running | awaiting_review | done | failed | rejected
    steps: List[StepResult] = field(default_factory=list)
    # Serializable working state (copy, design_id, export paths, ...) so a run
    # paused at a review gate resumes with everything earlier steps produced.
    context: Dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=now_iso)
    updated_at: str = field(default_factory=now_iso)

    def to_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        d["steps"] = [s if isinstance(s, dict) else s.to_dict() for s in d["steps"]]
        return d

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "PipelineRun":
        d = dict(d)
        d["steps"] = [StepResult(**s) for s in d.get("steps", [])]
        return cls(**d)

    @property
    def current_gate(self) -> Optional[str]:
        """Name of the step currently awaiting review, if any."""
        for s in self.steps:
            if s.status == "awaiting_review":
                return s.step
        return None
